# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/13684/Desktop/1year2/logicDesign/BigAssignment/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball86/ball86.xci
# IP: The module: 'ball86' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/13684/Desktop/1year2/logicDesign/BigAssignment/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball86_3/ball86_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ball86'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/13684/Desktop/1year2/logicDesign/BigAssignment/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball86/ball86.xci
# IP: The module: 'ball86' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/13684/Desktop/1year2/logicDesign/BigAssignment/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball86_3/ball86_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ball86'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
