# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/output_new_gameover_8/output_new_gameover.xci
# IP: The module: 'output_new_gameover' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/output_new_gameover_10/output_new_gameover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_new_gameover'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/output_new_gameover_8/output_new_gameover.xci
# IP: The module: 'output_new_gameover' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/output_new_gameover_10/output_new_gameover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_new_gameover'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
