# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 8
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.cache/wt [current_project]
set_property parent.project_path D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output90.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output80.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output92.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output86.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output62.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_vic_1.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_over_1.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/output_new.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_vic_2.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_over_2.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_over_4.coe
add_files D:/git_repo/DataDesign_FinalProject/Project/imgs/coes/output_over_5.coe
read_verilog -library xil_defaultlib {
  D:/git_repo/DataDesign_FinalProject/Project/code/Hex2Seg.v
  D:/git_repo/DataDesign_FinalProject/Project/code/HexTo8SEG.v
  D:/git_repo/DataDesign_FinalProject/Project/code/MyMC14495.vf
  D:/git_repo/DataDesign_FinalProject/Project/code/P2S_IO.v
  D:/git_repo/DataDesign_FinalProject/Project/code/Sseg_Dev.v
  D:/git_repo/DataDesign_FinalProject/Project/code/ball_control.v
  D:/git_repo/DataDesign_FinalProject/Project/code/ballbounce.v
  D:/git_repo/DataDesign_FinalProject/Project/code/clkdiv.v
  D:/git_repo/DataDesign_FinalProject/Project/code/counter_64.v
  D:/git_repo/DataDesign_FinalProject/Project/code/flocation.v
  D:/git_repo/DataDesign_FinalProject/Project/code/map.v
  D:/git_repo/DataDesign_FinalProject/Project/code/ps2_keyboard.v
  D:/git_repo/DataDesign_FinalProject/Project/code/update_xy.v
  D:/git_repo/DataDesign_FinalProject/Project/code/vga_display.v
  D:/git_repo/DataDesign_FinalProject/Project/code/vgac.v
  D:/git_repo/DataDesign_FinalProject/Project/code/top.v
}
read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/output_vic_4/output_vic.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/output_vic_4/output_vic_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball92/ball92.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball92_3/ball92_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball/ball.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball/ball_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball86/ball86.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball86_3/ball86_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball62/ball62.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball62/ball62_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball90/ball90.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball90_2/ball90_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball80/ball80.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball80_5/ball80_ooc.xdc]

read_ip -quiet D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/output_new_gameover_8/output_new_gameover.xci
set_property used_in_implementation false [get_files -all d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/output_new_gameover_10/output_new_gameover_ooc.xdc]

read_edif D:/git_repo/DataDesign_FinalProject/Project/code/P2S.edf
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/git_repo/DataDesign_FinalProject/Project/constraints/top.xdc
set_property used_in_implementation false [get_files D:/git_repo/DataDesign_FinalProject/Project/constraints/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7k160tffg676-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
