# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball62/ball62.xci
# IP: The module: 'ball62' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball62/ball62_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ball62'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.srcs/sources_1/ip/ball62/ball62.xci
# IP: The module: 'ball62' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repo/DataDesign_FinalProject/Project/Rolling_ball/Rolling_ball.gen/sources_1/ip/ball62/ball62_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ball62'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
